/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 12-Jan-2025 00.03.39 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `app_global_params` CASCADE
;

DROP TABLE IF EXISTS `app_module` CASCADE
;

DROP TABLE IF EXISTS `mst_general_currency` CASCADE
;

DROP TABLE IF EXISTS `mst_general_deductor` CASCADE
;

DROP TABLE IF EXISTS `mst_general_department` CASCADE
;

DROP TABLE IF EXISTS `mst_general_other_cost` CASCADE
;

DROP TABLE IF EXISTS `mst_general_tax` CASCADE
;

DROP TABLE IF EXISTS `mst_general_terms` CASCADE
;

DROP TABLE IF EXISTS `mst_general_terms_detail` CASCADE
;

DROP TABLE IF EXISTS `mst_person_supplier` CASCADE
;

DROP TABLE IF EXISTS `mst_sku` CASCADE
;

DROP TABLE IF EXISTS `mst_sku_business_type` CASCADE
;

DROP TABLE IF EXISTS `mst_sku_detail` CASCADE
;

DROP TABLE IF EXISTS `mst_sku_model` CASCADE
;

DROP TABLE IF EXISTS `mst_sku_packaging` CASCADE
;

DROP TABLE IF EXISTS `mst_sku_process` CASCADE
;

DROP TABLE IF EXISTS `mst_sku_type` CASCADE
;

DROP TABLE IF EXISTS `mst_sku_unit` CASCADE
;

DROP TABLE IF EXISTS `trans_purchase_order` CASCADE
;

DROP TABLE IF EXISTS `trans_purchase_order_deduction` CASCADE
;

DROP TABLE IF EXISTS `trans_purchase_order_detail` CASCADE
;

DROP TABLE IF EXISTS `trans_purchase_order_othercost` CASCADE
;

DROP TABLE IF EXISTS `trans_sku_minofqty` CASCADE
;

DROP TABLE IF EXISTS `trans_sku_minofstock` CASCADE
;

DROP TABLE IF EXISTS `trans_sku_pricelist` CASCADE
;

/* Create Tables */

CREATE TABLE `app_global_params`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`param_name` VARCHAR(100) NULL,
	`value_text` VARCHAR(255) NULL,
	`value_numeric` INT NULL,
	`value_decimal` DECIMAL(20,4) NULL,
	`value_date` DATE NULL,
	`value_timestamp` TIMESTAMP NULL,
	`flag_active` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	CONSTRAINT `PK_app_global_params` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `app_module`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(100) NULL,
	`prefix` VARCHAR(50) NULL,
	`flag_active` BOOL NULL,
	`flag_show` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	CONSTRAINT `PK_app_module` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `mst_general_currency`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(100) NULL,
	`prefix` VARCHAR(50) NULL,
	`flag_active` BOOL NULL,
	`flag_show` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	CONSTRAINT `PK_mst_general_currency` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `mst_general_deductor`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(100) NULL,
	`prefix` VARCHAR(50) NULL,
	`flag_active` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	`app_module_id` BIGINT NULL,
	CONSTRAINT `PK_mst_general_deductor` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `mst_general_department`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(100) NULL,
	`prefix` VARCHAR(50) NULL,
	`flag_active` BOOL NULL,
	`flag_show` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	`gen_cost_center_id` BIGINT NULL,
	CONSTRAINT `PK_mst_general_department` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `mst_general_other_cost`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(100) NULL,
	`prefix` VARCHAR(50) NULL,
	`flag_active` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	`app_module_id` BIGINT NULL,
	CONSTRAINT `PK_mst_general_other_cost` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `mst_general_tax`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(100) NULL,
	`prefix` VARCHAR(50) NULL,
	`value` DECIMAL(20,4) NULL,
	`flag_active` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	CONSTRAINT `PK_mst_general_tax` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `mst_general_terms`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(100) NULL,
	`prefix` VARCHAR(50) NULL,
	`flag_active` BOOL NULL,
	`flag_show` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	`app_module_id` BIGINT NULL,
	CONSTRAINT `PK_mst_general_terms` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `mst_general_terms_detail`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(100) NULL,
	`flag_active` BOOL NULL,
	`flag_show` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	`general_terms_id` BIGINT NULL,
	CONSTRAINT `PK_mst_general_terms_detail` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `mst_person_supplier`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(100) NULL,
	`prefix` VARCHAR(50) NULL,
	`address_01` TEXT NULL,
	`address_02` TEXT NULL,
	`address_03` TEXT NULL,
	`phone_01` VARCHAR(50) NULL,
	`phone_02` VARCHAR(50) NULL,
	`phone_03` VARCHAR(50) NULL,
	`fax_01` VARCHAR(50) NULL,
	`fax_02` VARCHAR(50) NULL,
	`fax_03` VARCHAR(50) NULL,
	`email_01` VARCHAR(50) NULL,
	`email_02` VARCHAR(50) NULL,
	`email_03` VARCHAR(50) NULL,
	`contact_person_01` VARCHAR(50) NULL,
	`contact_person_02` VARCHAR(50) NULL,
	`contact_person_03` VARCHAR(50) NULL,
	`flag_active` BOOL NULL,
	`flag_show` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	CONSTRAINT `PK_mst_person_supplier` PRIMARY KEY (`id` ASC)
);

CREATE TABLE `mst_factory_warehouse`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(100) NULL,
	`prefix` VARCHAR(50) NULL,
	`flag_active` BOOL NULL,
	`flag_show` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	CONSTRAINT `PK_mst_factory_warehouse` PRIMARY KEY (`id` ASC)
);


CREATE TABLE `mst_factory_machine`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(100) NULL,
	`prefix` VARCHAR(50) NULL,
	`flag_active` BOOL NULL,
	`flag_show` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	CONSTRAINT `PK_mst_factory_machine` PRIMARY KEY (`id` ASC)
);

CREATE TABLE `mst_sku`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(100) NULL,
	`prefix` VARCHAR(50) NULL,
	`flag_active` BOOL NULL,
	`flag_show` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	`sku_type_id` BIGINT NULL,
	`sku_unit_id` BIGINT NULL,
	`sku_model_id` BIGINT NULL,
	`sku_process_id` BIGINT NULL,
	`sku_business_type_id` BIGINT NULL,
	`sku_packaging_id` BIGINT NULL,
	`sku_detail_id` BIGINT NULL,
	CONSTRAINT `PK_mst_sku` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `mst_sku_business_type`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(100) NULL,
	`prefix` VARCHAR(50) NULL,
	`flag_active` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	CONSTRAINT `PK_mst_sku_business_type` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `mst_sku_detail`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`description` TEXT NULL,
	`flag_active` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	CONSTRAINT `PK_mst_sku_detail` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `mst_sku_model`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(100) NULL,
	`prefix` VARCHAR(50) NULL,
	`image_path` TEXT NULL,
	`flag_active` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	CONSTRAINT `PK_mst_sku_model` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `mst_sku_packaging`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(100) NULL,
	`prefix` VARCHAR(50) NULL,
	`flag_active` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	CONSTRAINT `PK_mst_sku_packaging` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `mst_sku_process`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(100) NULL,
	`prefix` VARCHAR(50) NULL,
	`flag_active` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	CONSTRAINT `PK_mst_sku_process` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `mst_sku_type`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(100) NULL,
	`prefix` VARCHAR(50) NULL,
	`flag_active` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	CONSTRAINT `PK_mst_sku_type` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `mst_sku_unit`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(100) NULL,
	`prefix` VARCHAR(50) NULL,
	`flag_active` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	CONSTRAINT `PK_mst_sku_unit` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `trans_purchase_order`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`trans_date` DATE NULL,
	`description` VARCHAR(100) NULL,
	`doc_num` VARCHAR(50) NULL,
	`doc_counter` SMALLINT NULL,
	`flag_status` SMALLINT NULL,
	`valid_from_date` DATE NULL,
	`valid_to_date` DATE NULL,
	`revision` SMALLINT NULL,
	`flag_type` SMALLINT NULL COMMENT '1 : production project material
	2 : general item',
	`flag_active` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	`gen_terms_detail_id` BIGINT NULL,
	`gen_currency_id` BIGINT NULL,
	`gen_department_id` BIGINT NULL,
	`prs_supplier_id` BIGINT NULL,
	CONSTRAINT `PK_trans_purchase_order` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `trans_purchase_order_deduction`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(100) NULL,
	`value_d` DECIMAL(20,4) NULL,
	`value_f` DECIMAL(20,4) NULL,
	`qty` DECIMAL(20,4) NULL,
	`total_d` DECIMAL(20,4) NULL,
	`total_f` DECIMAL(20,4) NULL,
	`counter` SMALLINT NULL,
	`flag_active` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	`trans_po_id` BIGINT NULL,
	`gen_deductor_id` BIGINT NULL,
	CONSTRAINT `PK_trans_purchase_order_deduction` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `trans_purchase_order_detail`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(100) NULL,
	`sku_description` VARCHAR(100) NULL,
	`sku_prefix` VARCHAR(50) NULL,
	`price_d` VARCHAR(50) NULL,
	`price_f` VARCHAR(50) NULL,
	`qty` VARCHAR(50) NULL,
	`subtotal_d` VARCHAR(50) NULL,
	`subtotal_f` VARCHAR(50) NULL,
	`discount_flag` VARCHAR(50) NULL,
	`discount_percentage` VARCHAR(50) NULL,
	`discount_d` VARCHAR(50) NULL,
	`discount_f` VARCHAR(50) NULL,
	`afterdiscount_d` VARCHAR(50) NULL,
	`afterdiscount_f` VARCHAR(50) NULL,
	`vat_flag` VARCHAR(50) NULL,
	`vat_percentage` VARCHAR(50) NULL,
	`vat_d` VARCHAR(50) NULL,
	`vat_f` VARCHAR(50) NULL,
	`total_d` VARCHAR(50) NULL,
	`total_f` VARCHAR(50) NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	`trans_po_id` BIGINT NULL,
	`sku_id` BIGINT NULL,
	CONSTRAINT `PK_trans_purchase_order_detail` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `trans_purchase_order_othercost`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(100) NULL,
	`value_d` DECIMAL(20,4) NULL,
	`value_f` DECIMAL(20,4) NULL,
	`qty` DECIMAL(20,4) NULL,
	`total_d` DECIMAL(20,4) NULL,
	`total_f` DECIMAL(20,4) NULL,
	`counter` SMALLINT NULL,
	`flag_active` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	`trans_po_id` BIGINT NULL,
	`gen_othercost_id` BIGINT NULL,
	CONSTRAINT `PK_trans_purchase_order_deduction` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `trans_sku_minofqty`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`qty` DECIMAL(20,4) NULL,
	`flag_active` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	`sku_id` BIGINT NULL,
	CONSTRAINT `PK_trans_sku_minofqty` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `trans_sku_minofstock`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`qty` DECIMAL(20,4) NULL,
	`flag_active` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	`sku_id` BIGINT NULL,
	CONSTRAINT `PK_trans_sku_minofstock` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `trans_sku_pricelist`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`price` DECIMAL(20,4) NULL,
	`flag_active` BOOL NULL,
	`created_by` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_by` VARCHAR(50) NULL,
	`updated_at` TIMESTAMP NULL,
	`deleted_by` VARCHAR(50) NULL,
	`deleted_at` TIMESTAMP NULL,
	`manual_id` VARCHAR(50) NULL,
	`generated_id` VARCHAR(32) NULL,
	`sku_id` BIGINT NULL,
	`gen_currency_id` BIGINT NULL,
	`prs_supplier_id` BIGINT NULL,
	CONSTRAINT `PK_trans_sku_pricelist` PRIMARY KEY (`id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `mst_general_deductor` 
 ADD INDEX `IXFK_mst_general_deductor_app_module` (`app_module_id` ASC)
;

ALTER TABLE `mst_general_other_cost` 
 ADD INDEX `IXFK_mst_general_other_cost_app_module` (`app_module_id` ASC)
;

ALTER TABLE `mst_general_terms` 
 ADD INDEX `IXFK_mst_terms_app_module` (`app_module_id` ASC)
;

ALTER TABLE `mst_sku` 
 ADD INDEX `IXFK_mst_sku_mst_sku_business_type` (`sku_business_type_id` ASC)
;

ALTER TABLE `mst_sku` 
 ADD INDEX `IXFK_mst_sku_mst_sku_detail` (`sku_detail_id` ASC)
;

ALTER TABLE `mst_sku` 
 ADD INDEX `IXFK_mst_sku_mst_sku_model` (`sku_model_id` ASC)
;

ALTER TABLE `mst_sku` 
 ADD INDEX `IXFK_mst_sku_mst_sku_packaging` (`sku_packaging_id` ASC)
;

ALTER TABLE `mst_sku` 
 ADD INDEX `IXFK_mst_sku_mst_sku_process` (`sku_process_id` ASC)
;

ALTER TABLE `mst_sku` 
 ADD INDEX `IXFK_mst_sku_mst_sku_type` (`sku_type_id` ASC)
;

ALTER TABLE `mst_sku` 
 ADD INDEX `IXFK_mst_sku_mst_sku_unit` (`sku_unit_id` ASC)
;

ALTER TABLE `trans_sku_minofqty` 
 ADD INDEX `IXFK_trans_sku_minofqty_mst_sku` (`sku_id` ASC)
;

ALTER TABLE `trans_sku_minofstock` 
 ADD INDEX `IXFK_trans_sku_minofstock_mst_sku` (`sku_id` ASC)
;

ALTER TABLE `trans_sku_pricelist` 
 ADD INDEX `IXFK_trans_sku_pricelist_mst_general_currency` (`gen_currency_id` ASC)
;

ALTER TABLE `trans_sku_pricelist` 
 ADD INDEX `IXFK_trans_sku_pricelist_mst_person_supplier` (`prs_supplier_id` ASC)
;

ALTER TABLE `trans_sku_pricelist` 
 ADD INDEX `IXFK_trans_sku_pricelist_mst_sku` (`sku_id` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `mst_general_deductor` 
 ADD CONSTRAINT `FK_mst_general_deductor_app_module`
	FOREIGN KEY (`app_module_id`) REFERENCES `app_module` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `mst_general_other_cost` 
 ADD CONSTRAINT `FK_mst_general_other_cost_app_module`
	FOREIGN KEY (`app_module_id`) REFERENCES `app_module` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `mst_general_terms` 
 ADD CONSTRAINT `FK_mst_terms_app_module`
	FOREIGN KEY (`app_module_id`) REFERENCES `app_module` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `mst_general_terms_detail` 
 ADD CONSTRAINT `FK_mst_general_terms_detail_mst_general_terms`
	FOREIGN KEY (`general_terms_id`) REFERENCES `mst_general_terms` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `mst_sku` 
 ADD CONSTRAINT `FK_mst_sku_mst_sku_business_type`
	FOREIGN KEY (`sku_business_type_id`) REFERENCES `mst_sku_business_type` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `mst_sku` 
 ADD CONSTRAINT `FK_mst_sku_mst_sku_detail`
	FOREIGN KEY (`sku_detail_id`) REFERENCES `mst_sku_detail` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `mst_sku` 
 ADD CONSTRAINT `FK_mst_sku_mst_sku_model`
	FOREIGN KEY (`sku_model_id`) REFERENCES `mst_sku_model` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `mst_sku` 
 ADD CONSTRAINT `FK_mst_sku_mst_sku_packaging`
	FOREIGN KEY (`sku_packaging_id`) REFERENCES `mst_sku_packaging` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `mst_sku` 
 ADD CONSTRAINT `FK_mst_sku_mst_sku_process`
	FOREIGN KEY (`sku_process_id`) REFERENCES `mst_sku_process` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `mst_sku` 
 ADD CONSTRAINT `FK_mst_sku_mst_sku_type`
	FOREIGN KEY (`sku_type_id`) REFERENCES `mst_sku_type` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `mst_sku` 
 ADD CONSTRAINT `FK_mst_sku_mst_sku_unit`
	FOREIGN KEY (`sku_unit_id`) REFERENCES `mst_sku_unit` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `trans_purchase_order_deduction` 
 ADD CONSTRAINT `FK_trans_purchase_order_deduction_mst_general_deductor`
	FOREIGN KEY (`gen_deductor_id`) REFERENCES `mst_general_deductor` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `trans_purchase_order_deduction` 
 ADD CONSTRAINT `FK_trans_purchase_order_deduction_trans_purchase_order`
	FOREIGN KEY (`trans_po_id`) REFERENCES `trans_purchase_order` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `trans_purchase_order_detail` 
 ADD CONSTRAINT `FK_trans_purchase_order_detail_mst_sku`
	FOREIGN KEY (`sku_id`) REFERENCES `mst_sku` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `trans_purchase_order_detail` 
 ADD CONSTRAINT `FK_trans_purchase_order_detail_trans_purchase_order`
	FOREIGN KEY (`trans_po_id`) REFERENCES `trans_purchase_order` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `trans_purchase_order_othercost` 
 ADD CONSTRAINT `FK_trans_purchase_order_othercost_mst_general_other_cost`
	FOREIGN KEY (`gen_othercost_id`) REFERENCES `mst_general_other_cost` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `trans_purchase_order_othercost` 
 ADD CONSTRAINT `FK_trans_purchase_order_othercost_trans_purchase_order`
	FOREIGN KEY (`trans_po_id`) REFERENCES `trans_purchase_order` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `trans_sku_minofqty` 
 ADD CONSTRAINT `FK_trans_sku_minofqty_mst_sku`
	FOREIGN KEY (`sku_id`) REFERENCES `mst_sku` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `trans_sku_minofstock` 
 ADD CONSTRAINT `FK_trans_sku_minofstock_mst_sku`
	FOREIGN KEY (`sku_id`) REFERENCES `mst_sku` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `trans_sku_pricelist` 
 ADD CONSTRAINT `FK_trans_sku_pricelist_mst_general_currency`
	FOREIGN KEY (`gen_currency_id`) REFERENCES `mst_general_currency` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `trans_sku_pricelist` 
 ADD CONSTRAINT `FK_trans_sku_pricelist_mst_person_supplier`
	FOREIGN KEY (`prs_supplier_id`) REFERENCES `mst_person_supplier` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `trans_sku_pricelist` 
 ADD CONSTRAINT `FK_trans_sku_pricelist_mst_sku`
	FOREIGN KEY (`sku_id`) REFERENCES `mst_sku` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1
; 
